### ISSUE TITLE
[Major Bug] Cannot swap weapons by pressing 'e' or 'E'

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [rm21845/themysterymachine#50]
# Description of the bug

While playing the game I was not able to swap weapons on the ground by pressing 'e' or 'E'

# Video Description

I have made a video depicting the type of bug I faced while playing the game. Go to the link provided to understand the issue.

https://youtu.be/ePLMhJroPwA

**Comment by natebud** [comment]
Picking up weapons is not proximity based and you must actually place the crosshair over the weapon you want to pick up before you press 'e.' This was a design choice to ensure that there was no confusion when picking up a specific gun when multiple guns were nearby. However the README did improperly state that you could pick up a weapon by walking over it, and it has since been revised.
